---
name: Label Checker
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - unlabeled

jobs:

  check_labels:
    name: Check labels
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    steps:
      - uses: docker://onsdigital/github-pr-label-checker@sha256:57dfb736dcf5c2e317c5fb7bdbc93161105c8ff149fa8c87742802bf2e9a3d07 # v1.6.65
        with:
          one_of: breaking change,feature,patch
          none_of: do not merge,work in progress
          repo_token: ${{ secrets.GITHUB_TOKEN }}
